[build]
builder = "nixpacks"

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.build]
cmds = ["python3 -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "sleep infinity"
